#need to enable vscode rest client extension https://marketplace.visualstudio.com/items?itemName=humao.rest-client to send requests

# GET http://127.0.0.1:8080/api/cats/?limit=10&id=65&name=murzik&color=blue&select=id,name HTTP/1.1
# Accept: */*
# project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###
 
POST http://127.0.0.1:8080/api/cats/batch HTTP/1.1
Accept: */*
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

[
    {
        "name": "1111111111",
        "color": "11111111111"
    },
    {
        "name": "222222222",
        "color": "2222222"
    }
]

###

POST http://127.0.0.1:8080/api/cats HTTP/1.1
Accept: */*
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "name": "first_test_name_create",
    "color": "first_test_color_create"
}

###

DELETE http://127.0.0.1:8080/api/cats/55 HTTP/1.1
Accept: */*
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

DELETE http://127.0.0.1:8080/api/cats/search HTTP/1.1
Accept: */*
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "id": [136],
    "name":[
        {
            "regex":"^tesft_namfe$",
            "conjuctive_operator":"Or"
        }
    ],
    "color":[
        {
            "regex":"test",
            "conjuctive_operator":"Or"
        }
    ]
}

### todo name and color must be  arrays              

DELETE http://127.0.0.1:8080/api/cats?id=161,162&name=first_test_name_create,fdf&color=first_test_color_create,blue HTTP/1.1
Accept: */*
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/api/cats/162?&select=IdName HTTP/1.1
Accept: */*
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

POST http://127.0.0.1:8080/api/cats/search HTTP/1.1
Accept: */*
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "select": "Id",
    "id": [136,138],
    "name":[
        {
            "regex":"^tesft_namfe$",
            "conjuctive_operator":"Or"
        }
    ],
    "color":[
        {
            "regex":"test",
            "conjuctive_operator":"Or"
        }
    ],
    "order_by": {
        "column": "id",
        "order": "desc"
    },
    "limit": 10,
    "offset": 0
}

###   

GET http://127.0.0.1:8080/api/cats?limit=10&id=136&name=test_name,test_nam&color=test_color&select=IdName&order_by=column=id,order=asc&offset=1 HTTP/1.1
Accept: */*
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

PATCH http://127.0.0.1:8080/api/cats/168 HTTP/1.1
Accept: */*
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "name": "namef",
    "color":"colorf"
}

### fix this

PATCH http://127.0.0.1:8080/api/cats/batch HTTP/1.1
Accept: */* 
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

[
    {
        "id": 136,
        "name": "34535345me",
        "color":"1343243e"
    },
    {
        "id": 136,
        "name": "s23452345dddddddddddsdod",
        "color":"secosdd25432523453ddddddfnd"
    }
]

###

GET http://127.0.0.1:8080/health_check HTTP/1.1
Accept: */*

###

GET http://127.0.0.1:8080/git_info HTTP/1.1
Accept: */*

###

GET http://127.0.0.1:8080/src/main.rs HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/header_extractor_example HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/extract_custom_header_example HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/middleware_message_example HTTP/1.1

###

GET http://127.0.0.1:8080/read_middleware_custom_header HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696