#need to enable vscode rest client extension https://marketplace.visualstudio.com/items?itemName=humao.rest-client to send requests

# GET http://127.0.0.1:8080/api/cats/?limit=10&id=65&name=murzik&color=blue&select=id,name HTTP/1.1
# Accept: */*
# project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

GET http://127.0.0.1:8080/api/cats/?limit=10&id=57,54,51,65&name=test_name,test_nameee&color=test_color&select=id,name,color&order_by=order=desc,column=name HTTP/1.1
Accept: */*
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/api/cats/?limit=10&id=57,54,51,65&name=test_name,test_nameee&color=test_color&select=id,name,color&order_by=id.asc HTTP/1.1
Accept: */*
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/api/cats/65?&select=id,name HTTP/1.1
Accept: */*
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

POST http://127.0.0.1:8080/api/cats/ HTTP/1.1
Accept: */*
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "name": "tesft_namfe",
    "color": "testd_colort"
}

###

PUT http://127.0.0.1:8080/api/cats/ HTTP/1.1
Accept: */*
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "id": 1,
    "name": "test_name",
    "color": "test_color"
}

###

PATCH http://127.0.0.1:8080/api/cats/1 HTTP/1.1
Accept: */*
content-type: application/json
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

{
    "NameColor": {
        "name": "kdfsdd",
        "color":"testcatnamepatched123"
    }
}

###

DELETE http://127.0.0.1:8080/api/cats/?name=kek&color=white HTTP/1.1
Accept: */*
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

DELETE http://127.0.0.1:8080/api/cats/1 HTTP/1.1
Accept: */*
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/health_check HTTP/1.1
Accept: */*

###

GET http://127.0.0.1:8080/git_info HTTP/1.1
Accept: */*

###

GET http://127.0.0.1:8080/src/main.rs HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/header_extractor_example HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/extract_custom_header_example HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696

###

GET http://127.0.0.1:8080/middleware_message_example HTTP/1.1

###

GET http://127.0.0.1:8080/read_middleware_custom_header HTTP/1.1
project_commit: a07b8a91a46a2aa9c1bfce5d306811a37edba696